travis:
  secure:
    BINSTAR_TOKEN: FWziB2nBJ/vVtgzJRNOACWmyhZuz+CDOJObUNKYPisI0vDTjKVGaOenHPhLS1NYx6u8dMOQuVXI8cZiXlddvTORj0sHm2iSpESPiRSikcrZm2VsY110000gaDRPOMt44ISdrqJtcxEkgayh7wETPoxx0LOfWVrMWfURPxK5v8lvf2NAXUzMnqdfYkaLZZJ81zxP47MzeDVzaUXUJy4r0UokKCTVQ0BfI8FfFIuLLvNr0SnVl4UM8eO1kzTZ7SiCgms/kJcXb+5wdq1N7SmQCfbflI94og5OCWuF7rh1H7mgQw7jmEVDn/w9M3l7aBqSRIyqnWE5Ewf0TPIgPp/hFW8C4XUyfLUuDlLndQvQC758d64ogNCpMQLgs/nSCYDNCl+b6seaSFS5thcWxe1sPHjz8HwU2ugG8YGPJTRp87ohHyciGk501uhIAIkaTfaVaLTPugfdnllw1zWCiwEv19cDeFbS2AVfMs+Zatx2VfroYY/5H9o84PcKrGeCgLQnRWvW3JFQrrJzoa0qBTEwmQZDAu2nacYvaS2Q+3Kne/5EM7dpjMNtmohIrnRiUm9Hf0VRjNTkp1M/VHPCZ9f7gfThQ7+0y/OKhb+5av6R7bsvyvGcFymTNGusHJOjAkkmdqBZa4OvFXA2eIgU0vQG33FcnNIazcaZIbzYlb9I88sg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
